SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;

ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

CREATE USER c##dbzuser IDENTIFIED BY dbz QUOTA UNLIMITED ON USERS CONTAINER=ALL;
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE PROCEDURE, SELECT ANY TABLE, SELECT ANY DICTIONARY, SELECT ANY TRANSACTION, LOGMINING, EXECUTE_CATALOG_ROLE TO c##dbzuser CONTAINER=ALL;
